### ISSUE TITLE
[BUG] Get row values uses getValue and not tryGetValue

### ISSUE THREAD

**Issue by Freymaurer** [CSBiology/FSharpSpreadsheetML#11]
**Describe the bug**
I tried to access row values of unknown number. The following code snippet will error at the first row with an empty cell.
This behaviour is due to the cell having a green background and therefore being parsed as part of the row.

```fsharp
SheetData.getRows sheetData
|> Array.ofSeq
|> Array.map (fun row ->
    Row.getValues sst row |> Array.ofSeq
)
```

**Expected behavior**
I was expecting to get a sequence of all found terms and in case of an empty cell to simply not get a value for it.

Maybe implement `Row.getValues` and all similiar functions to use `Cell.tryGetValue` instead of `Cell.getValue` and filter to only return found values (`Seq.choose` or something).
And add a Row.tryGetValues version which returns with `seq<string option>` as output.

**Screenshots**
![image](https://user-images.githubusercontent.com/39732517/137336492-9ecae5d5-67f8-4789-b4a1-8c5164c5a6cf.png)

**Comment by omaus** [comment]
```f#
SheetData.getRows sheetData
|> Array.ofSeq
|> Array.map (fun row ->
    Row.getValues sst row |> Array.ofSeq
)
```

`Row.getValues` is not defined in FSharpSpreadsheetML, v0.0.7. Which function do you mean? `Row.getRowValues`?

**Comment by Freymaurer** [comment]
> ```fsharp
> SheetData.getRows sheetData
> |> Array.ofSeq
> |> Array.map (fun row ->
>     Row.getValues sst row |> Array.ofSeq
> )
> ```
> 
> `Row.getValues` is not defined in FSharpSpreadsheetML, v0.0.7. Which function do you mean? `Row.getRowValues`?

Yes exactly, it was `Row.getRowValues`.
